-- MySQL Script generated by MySQL Workbench
-- 13.04.2016 (ср) 16,52,54 EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `store_db` ;

-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store_db` DEFAULT CHARACTER SET utf8 ;
USE `store_db` ;

-- -----------------------------------------------------
-- Table `store_db`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`addresses` (
  `id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`customers` (
  `id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(250) NULL DEFAULT NULL,
  `lname` VARCHAR(250) NOT NULL,
  `addresses_id` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `addresses_id`),
  INDEX `fk_customers_addresses_idx` (`addresses_id` ASC),
  CONSTRAINT `fk_customers_addresses`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `store_db`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`orders` (
  `id` INT(7) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_datetime` DATETIME NOT NULL,
  `customers_id` SMALLINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `customers_id`),
  INDEX `fk_orders_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `store_db`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_db`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`product_categories` (
  `id` SMALLINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`products` (
  `id` MEDIUMINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(250) NOT NULL,
  `short_desc` VARCHAR(250) NULL DEFAULT '',
  `long_desc` TINYTEXT NULL DEFAULT NULL,
  `price` DECIMAL(7,2) NULL DEFAULT NULL,
  `product_category_id` SMALLINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `product_category_id`),
  INDEX `fk_products_product_category1_idx` (`product_category_id` ASC),
  CONSTRAINT `fk_products_product_category1`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `store_db`.`product_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store_db`.`orders_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`orders_has_products` (
  `orders_id` INT(7) UNSIGNED NOT NULL,
  `products_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`orders_id`, `products_id`),
  INDEX `fk_orders_has_products_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `store_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `store_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
